name: ecsopendata
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - flask-admin
  - flask-login
  - flask-mail
  - flask-principal
  - flask-script
  - flask-security
  - flask-wtf
  - flask
  - pandas
  - xlrd
